stages:
  train:
    cmd: ploomber-engine mh.ipynb mh_output.ipynb
    deps:
      - maternal-health-and-high-risk-pregnancy-dataset.zip
      - mh.ipynb
    outs:
      - model1.pkl
      - test1.csv
      - mh_output.ipynb

  test:
    cmd: ploomber-engine evaluate.ipynb evaluate_output.ipynb
    deps:
      - test1.csv
      - evaluate.ipynb
      - model1.pkl
    outs:
      - evaluate_output.ipynb
      - cm_dataset1.png
    metrics:
      - metrics.json:
          cache: false